import {
  MessageSquare,
  DollarSign,
  Megaphone,
  Database,
  CheckSquare,
  Smartphone,
  XCircle,
  AlertTriangle,
  Compass,
  Activity,
  ShieldAlert,
  CreditCard,
  BarChart2,
  Zap,
  CheckCircle2,
} from 'lucide-react';

export const PRESETS = {
  automation: {
    name: 'Workspace Overview',
    icon: Compass,
    subtitle: 'Statistics overview',
    kpis: [
      {
        name: 'Workflows Executed',
        value: 14832,
        trend: '+10% ▲',
        state: 'success',
        suffix: 'Runs',
        sparkline: [11000, 11500, 12000, 12200, 12500, 13000, 14832],
      },
      {
        name: 'Total Data Processed',
        value: '12.1TB',
        trend: '+5% ▲',
        state: 'success',
        suffix: 'Processed',
        sparkline: [10.5, 10.8, 11.0, 11.2, 11.5, 11.8, 12.1],
      },
      {
        name: 'Success Rate',
        value: 99.8,
        trend: '+0.2% ▲',
        state: 'success',
        suffix: 'percent',
        sparkline: [99.1, 99.3, 99.5, 99.4, 99.6, 99.7, 99.8],
      },
      {
        name: 'Active Triggers',
        value: 42,
        trend: '+4 today',
        state: 'success',
        suffix: 'active nodes',
        sparkline: [36, 38, 38, 39, 40, 41, 42],
      },
    ],
    chartData: [
      { label: '22 Jan', value: 12000 },
      { label: '28 Jan', value: 14100 },
      { label: '2 Feb', value: 14900 },
      { label: '8 Feb', value: 15823 },
      { label: '14 Mar', value: 16412 },
    ],
    chartLabel: 'Workflow Executions',
    listTitle: 'Recent Activities',
    listItems: [
      {
        message: 'Invoice processing pipeline #892 completed successfully',
        time: 'Just now',
        state: 'success',
      },
      {
        message: 'HubSpot CRM sync synced 12,400 contacts',
        time: '15m ago',
        state: 'success',
      },
      {
        message: 'Slack notification trigger executed without errors',
        time: '42m ago',
        state: 'success',
      },
      {
        message: 'Database backup workflow completed and verified',
        time: '2h ago',
        state: 'info',
      },
    ],
    diagnosticMsg:
      'AI Diagnostic Pulse: Subscriber acquisition rate increased 10% this week. Daily visitor counts are showing a steady upward trend on key platforms.',
  },
  chatbot: {
    name: 'AI Chatbot',
    icon: MessageSquare,
    subtitle: 'Conversations, resolution rates, and live sessions',
    kpis: [
      {
        name: 'Total Conversations',
        value: 18492,
        trend: '+24.5%',
        state: 'success',
        suffix: 'chats',
        sparkline: [12000, 14000, 13500, 15000, 16800, 18000, 18492],
      },
      {
        name: 'AI Resolution Rate',
        value: 88.4,
        trend: '+3.1%',
        state: 'success',
        suffix: 'resolved',
        sparkline: [82.4, 84.1, 85.0, 86.8, 87.2, 88.0, 88.4],
      },
      {
        name: 'LLM Response Time',
        value: 1.2,
        trend: '-0.3s',
        state: 'success',
        suffix: 'speed (sec)',
        sparkline: [1.5, 1.45, 1.4, 1.35, 1.3, 1.24, 1.2],
      },
      {
        name: 'Active Chatbot Nodes',
        value: 8,
        trend: '+2 today',
        state: 'info',
        suffix: 'agents',
        sparkline: [4, 5, 5, 6, 6, 7, 8],
      },
    ],
    chartData: [
      { label: 'Mon', value: 2100 },
      { label: 'Tue', value: 2400 },
      { label: 'Wed', value: 2800 },
      { label: 'Thu', value: 2600 },
      { label: 'Fri', value: 3100 },
      { label: 'Sat', value: 1800 },
      { label: 'Sun', value: 1500 },
    ],
    chartLabel: 'Conversations',
    listTitle: 'Recent Support Interactions',
    listItems: [
      {
        message: 'AI resolved user question about invoice billing details',
        time: 'Just now',
        state: 'success',
      },
      {
        message: 'Chat escalated to live support - inquiry: enterprise custom SLA',
        time: '5m ago',
        state: 'warning',
      },
      {
        message: 'Product onboarding chat guide finished successfully',
        time: '18m ago',
        state: 'success',
      },
      {
        message: 'WhatsApp Business API sync updated successfully',
        time: '1h ago',
        state: 'success',
      },
    ],
    diagnosticMsg:
      'AI Diagnostic: Chatbot resolved 88.4% of queries without agent intervention. Response speeds optimized under high message volume.',
  },
  crm: {
    name: 'CRM & Sales',
    icon: DollarSign,
    subtitle: 'Sales pipeline, deals won, and lead acquisition',
    kpis: [
      {
        name: 'Pipeline Value',
        value: 842900,
        trend: '+18.2%',
        state: 'success',
        suffix: 'USD value',
        sparkline: [700000, 720000, 750000, 780000, 810000, 830000, 842900],
      },
      {
        name: 'Deals Auto-Logged',
        value: 47,
        trend: '+8 this month',
        state: 'success',
        suffix: 'deals',
        sparkline: [32, 35, 38, 40, 42, 45, 47],
      },
      {
        name: 'Lead Win Rate',
        value: 32.4,
        trend: '+2.1%',
        state: 'success',
        suffix: 'win rate (%)',
        sparkline: [28.2, 29.5, 30.1, 31.0, 31.4, 32.0, 32.4],
      },
      {
        name: 'AI Lead Confidence',
        value: 92.8,
        trend: '+1.5%',
        state: 'info',
        suffix: 'confidence (%)',
        sparkline: [90.5, 91.0, 91.2, 91.8, 92.0, 92.5, 92.8],
      },
    ],
    chartData: [
      { label: 'Mon', value: 6800 },
      { label: 'Tue', value: 7100 },
      { label: 'Wed', value: 7400 },
      { label: 'Thu', value: 7600 },
      { label: 'Fri', value: 8200 },
      { label: 'Sat', value: 8300 },
      { label: 'Sun', value: 8429 },
    ],
    chartLabel: 'Deals Value',
    listTitle: 'Recent Pipeline Updates',
    listItems: [
      {
        message: 'Lead Acme Corp upgraded to status: Demo Scheduled by AI',
        time: 'Just now',
        state: 'success',
      },
      {
        message: 'Deal TechVault Inc closed won - Value: $24,500',
        time: '15m ago',
        state: 'success',
      },
      {
        message: 'New inbound lead registered from organic landing page',
        time: '32m ago',
        state: 'success',
      },
      {
        message: 'Sales agent John Doe assigned to CloudStack account',
        time: '2h ago',
        state: 'info',
      },
    ],
    diagnosticMsg:
      'AI Diagnostic: Lead score accuracy increased by 5%. Recommendation: trigger follow-up sequences for 12 highly engaged leads.',
  },
  marketing: {
    name: 'Marketing Automation',
    icon: Megaphone,
    subtitle: 'Campaign status, conversion rates, and list growth',
    kpis: [
      {
        name: 'Active Campaigns',
        value: 12,
        trend: '+2 new',
        state: 'info',
        suffix: 'campaigns',
        sparkline: [8, 9, 9, 10, 11, 11, 12],
      },
      {
        name: 'Avg Click Rate',
        value: 4.85,
        trend: '+0.6%',
        state: 'success',
        suffix: 'CTR (%)',
        sparkline: [4.1, 4.3, 4.2, 4.5, 4.6, 4.8, 4.85],
      },
      {
        name: 'Campaign Conversions',
        value: 1582,
        trend: '+15.2%',
        state: 'success',
        suffix: 'conversions',
        sparkline: [1200, 1350, 1320, 1420, 1480, 1530, 1582],
      },
      {
        name: 'Total Emails Dispatched',
        value: 128400,
        trend: '+8,200',
        state: 'info',
        suffix: 'sent',
        sparkline: [100000, 105000, 112000, 118000, 122000, 125000, 128400],
      },
    ],
    chartData: [
      { label: 'Mon', value: 180 },
      { label: 'Tue', value: 210 },
      { label: 'Wed', value: 240 },
      { label: 'Thu', value: 220 },
      { label: 'Fri', value: 280 },
      { label: 'Sat', value: 150 },
      { label: 'Sun', value: 130 },
    ],
    chartLabel: 'Campaign Conversions',
    listTitle: 'Recent Campaign Triggers',
    listItems: [
      {
        message: 'Welcome newsletter delivered to 4,200 active users',
        time: 'Just now',
        state: 'success',
      },
      {
        message: 'Abandoned checkout campaign triggered for subscriber #8921',
        time: '22m ago',
        state: 'success',
      },
      {
        message: 'Lead score threshold reached for contact Alex Johnson',
        time: '40m ago',
        state: 'info',
      },
      {
        message: 'Google Ads campaign sync completed successfully',
        time: '3h ago',
        state: 'success',
      },
    ],
    diagnosticMsg:
      'AI Diagnostic: Conversions spike detected in Welcome sequence. Recommended: increase budget allocation on top-performing search ads.',
  },
  analytics: {
    name: 'Data Analytics',
    icon: Database,
    subtitle: 'Connected sources, ingestion rate, and query latency',
    kpis: [
      {
        name: 'Connected Sources',
        value: 14,
        trend: '+1 new',
        state: 'success',
        suffix: 'sources',
        sparkline: [10, 11, 12, 12, 13, 13, 14],
      },
      {
        name: 'Data Ingested',
        value: 4.2,
        trend: '+18.4%',
        state: 'success',
        suffix: 'TB volume',
        sparkline: [3.1, 3.3, 3.5, 3.7, 3.9, 4.0, 4.2],
      },
      {
        name: 'Avg Query Latency',
        value: 42,
        trend: '-4ms',
        state: 'success',
        suffix: 'latency (ms)',
        sparkline: [52, 49, 48, 45, 46, 43, 42],
      },
      {
        name: 'Model Runs Executed',
        value: 82,
        trend: '+6 updated',
        state: 'info',
        suffix: 'runs',
        sparkline: [68, 70, 72, 75, 78, 80, 82],
      },
    ],
    chartData: [
      { label: 'Mon', value: 1240 },
      { label: 'Tue', value: 1480 },
      { label: 'Wed', value: 1520 },
      { label: 'Thu', value: 1490 },
      { label: 'Fri', value: 1650 },
      { label: 'Sat', value: 820 },
      { label: 'Sun', value: 750 },
    ],
    chartLabel: 'Queries Executed',
    listTitle: 'Recent Data Analytics Events',
    listItems: [
      {
        message: 'Daily revenue analytics report exported successfully',
        time: 'Just now',
        state: 'success',
      },
      {
        message: 'Database sync completed for Postgres production replica',
        time: '18m ago',
        state: 'success',
      },
      {
        message: 'Index optimization resolved query latency warning on log_table',
        time: '55m ago',
        state: 'success',
      },
      {
        message: 'Data warehouse successfully loaded 450k event batches',
        time: '4h ago',
        state: 'success',
      },
    ],
    diagnosticMsg:
      'AI Diagnostic: Ingestion throughput remains optimal. P99 query latency is stable at 42ms with no replication lags detected.',
  },
  project: {
    name: 'Project Management',
    icon: CheckSquare,
    subtitle: 'Tasks completed, velocity, and blocker reports',
    kpis: [
      {
        name: 'Tasks Completed',
        value: 342,
        trend: '+18% wk',
        state: 'success',
        suffix: 'tasks',
        sparkline: [260, 280, 295, 310, 322, 335, 342],
      },
      {
        name: 'AI Sprint Velocity',
        value: 94,
        trend: '+6 pts',
        state: 'success',
        suffix: 'velocity pts',
        sparkline: [82, 85, 86, 88, 90, 92, 94],
      },
      {
        name: 'Team Alignment',
        value: 98,
        trend: '+1.2%',
        state: 'success',
        suffix: 'factor (%)',
        sparkline: [95, 96, 95.8, 97, 97.5, 98, 98],
      },
      {
        name: 'Active Blockers',
        value: 2,
        trend: '-3 resolved',
        state: 'success',
        suffix: 'blockers',
        sparkline: [6, 5, 4, 3, 3, 2, 2],
      },
    ],
    chartData: [
      { label: 'Mon', value: 42 },
      { label: 'Tue', value: 48 },
      { label: 'Wed', value: 52 },
      { label: 'Thu', value: 49 },
      { label: 'Fri', value: 56 },
      { label: 'Sat', value: 22 },
      { label: 'Sun', value: 15 },
    ],
    chartLabel: 'Tasks Completed',
    listTitle: 'Recent Task Activity',
    listItems: [
      {
        message: 'Task "Refactor navigation shell to light-mode" moved to Done',
        time: 'Just now',
        state: 'success',
      },
      {
        message: 'Sprint blocker resolved by developer: CORS headers updated',
        time: '15m ago',
        state: 'success',
      },
      {
        message: 'Sprint planning notes shared with product managers',
        time: '35m ago',
        state: 'info',
      },
      {
        message: 'Design review requested on pull request #89: layout updates',
        time: '2h ago',
        state: 'warning',
      },
    ],
    diagnosticMsg:
      'AI Diagnostic: Sprint velocity has increased by 7% this week. Blockers are being resolved within an average of 45 minutes.',
  },
  mobile: {
    name: 'Mobile App',
    icon: Smartphone,
    subtitle: 'Downloads, active users, and store evaluations',
    kpis: [
      {
        name: 'App Store Downloads',
        value: 84200,
        trend: '+14.5%',
        state: 'success',
        suffix: 'installs',
        sparkline: [70000, 72000, 74500, 78000, 80500, 83000, 84200],
      },
      {
        name: 'Daily Active Users',
        value: 18400,
        trend: '+8.2%',
        state: 'success',
        suffix: 'DAU',
        sparkline: [15000, 16200, 16000, 17100, 17500, 18100, 18400],
      },
      {
        name: 'Push Click-Through',
        value: 12.4,
        trend: '+1.1%',
        state: 'success',
        suffix: 'CTR (%)',
        sparkline: [10.2, 10.8, 11.1, 11.5, 11.9, 12.1, 12.4],
      },
      {
        name: 'Push Delivery Rate',
        value: 99.8,
        trend: '+0.1%',
        state: 'success',
        suffix: 'delivery (%)',
        sparkline: [99.6, 99.7, 99.7, 99.75, 99.8, 99.8, 99.8],
      },
    ],
    chartData: [
      { label: 'Mon', value: 15400 },
      { label: 'Tue', value: 16800 },
      { label: 'Wed', value: 17200 },
      { label: 'Thu', value: 17000 },
      { label: 'Fri', value: 18400 },
      { label: 'Sat', value: 14200 },
      { label: 'Sun', value: 13500 },
    ],
    chartLabel: 'Daily Active Users (DAU)',
    listTitle: 'Recent Mobile Events',
    listItems: [
      {
        message: 'New 5-star rating registered: "Saves me hours weekly!"',
        time: 'Just now',
        state: 'success',
      },
      {
        message: 'Push notification campaign delivered to 18,400 active users',
        time: '14m ago',
        state: 'success',
      },
      {
        message: 'iOS app package build 2.4.1 approved in App Store Connect',
        time: '40m ago',
        state: 'success',
      },
      {
        message: 'Crash-free sessions logged at 99.98% across all devices',
        time: '3h ago',
        state: 'success',
      },
    ],
    diagnosticMsg:
      'AI Diagnostic: Crash rates remain extremely low. Push campaign click-through reached a peak of 12.4% during early morning hours.',
  },
};

export const TIME_FILTERS = ['Today', '7 Days', '30 Days', '90 Days'] as const;

export const ALERTS = [
  {
    id: 'a1',
    type: 'error',
    icon: XCircle,
    message: 'Workflow #2841 failed - Slack timeout',
    time: '8m ago',
    color: 'text-red-500',
    bg: 'bg-red-500/8 dark:bg-red-950/20',
    border: 'border-red-500/15',
  },
  {
    id: 'a2',
    type: 'warning',
    icon: AlertTriangle,
    message: 'Slack Integration token expires in 2 days',
    time: '1h ago',
    color: 'text-amber-500',
    bg: 'bg-amber-500/8 dark:bg-amber-950/20',
    border: 'border-amber-500/15',
  },
  {
    id: 'a3',
    type: 'warning',
    icon: AlertTriangle,
    message: 'Credit balance below 20% threshold',
    time: '3h ago',
    color: 'text-amber-500',
    bg: 'bg-amber-500/8 dark:bg-amber-950/20',
    border: 'border-amber-500/15',
  },
];

export const TOP_INTEGRATIONS = [
  { name: 'OpenAI', usage: 94, color: '#10a37f', runs: '18,429', dot: 'bg-emerald-500' },
  { name: 'Slack', usage: 78, color: '#4A154B', runs: '12,831', dot: 'bg-purple-500' },
  { name: 'HubSpot', usage: 61, color: '#FF7A59', runs: '9,847', dot: 'bg-orange-500' },
  { name: 'Notion', usage: 44, color: '#000000', runs: '6,203', dot: 'bg-gray-600' },
  { name: 'Stripe', usage: 29, color: '#635BFF', runs: '4,018', dot: 'bg-indigo-500' },
];

export const TEAM_ACTIVITY = [
  {
    user: 'Sarah K.',
    action: 'created workflow',
    target: 'HubSpot -> Notion Sync',
    avatar: 'SK',
    color: 'bg-violet-500',
    time: '4m ago',
  },
  {
    user: 'James M.',
    action: 'updated automation',
    target: 'Stripe Invoice Drip',
    avatar: 'JM',
    color: 'bg-sky-500',
    time: '18m ago',
  },
  {
    user: 'Alex R.',
    action: 'connected integration',
    target: 'Slack -> OrbitFlow',
    avatar: 'AR',
    color: 'bg-emerald-600',
    time: '42m ago',
  },
  {
    user: 'Priya D.',
    action: 'generated report',
    target: 'Q2 Execution Summary',
    avatar: 'PD',
    color: 'bg-pink-500',
    time: '1h ago',
  },
];

export const NOTIFICATIONS = [
  {
    id: 'n1',
    type: 'system',
    message: 'Data warehouse loaded 450k event batches successfully. All pipelines active.',
    time: '4h ago',
    icon: Activity,
    color: 'text-emerald-500',
  },
  {
    id: 'n2',
    type: 'system',
    message: 'Index optimization resolved query latency warning in production database.',
    time: '55m ago',
    icon: ShieldAlert,
    color: 'text-emerald-500',
  },
  {
    id: 'n3',
    type: 'billing',
    message: 'Your monthly invoice for May has been generated and is ready for download.',
    time: '3h ago',
    icon: CreditCard,
    color: 'text-[var(--orbit-accent-primary)]',
  },
  {
    id: 'n4',
    type: 'all',
    message: 'Daily revenue analytics report exported successfully.',
    time: 'Just now',
    icon: BarChart2,
    color: 'text-[var(--orbit-accent-primary)]',
  },
  {
    id: 'n5',
    type: 'system',
    message: 'Workflow deployment successful for user sync job.',
    time: '1h ago',
    icon: Activity,
    color: 'text-emerald-500',
  },
  {
    id: 'n6',
    type: 'billing',
    message: 'Payment received for Enterprise plan upgrade.',
    time: '5h ago',
    icon: CreditCard,
    color: 'text-emerald-500',
  },
  {
    id: 'n7',
    type: 'all',
    message: 'Warning: High memory usage detected on cluster worker nodes.',
    time: '6h ago',
    icon: ShieldAlert,
    color: 'text-amber-500',
  },
  {
    id: 'n8',
    type: 'system',
    message: 'Automated database backup completed.',
    time: '12h ago',
    icon: Database,
    color: 'text-blue-500',
  },
  {
    id: 'n9',
    type: 'all',
    message: 'New user joined: alex@starkindustries.com',
    time: '1d ago',
    icon: Activity,
    color: 'text-emerald-500',
  },
  {
    id: 'n10',
    type: 'all',
    message: 'Daily revenue analytics report exported successfully.',
    time: '2d ago',
    icon: BarChart2,
    color: 'text-[var(--orbit-accent-primary)]',
  },
  {
    id: 'n11',
    type: 'system',
    message: 'Workflow deployment successful for user sync job.',
    time: '2d ago',
    icon: Activity,
    color: 'text-emerald-500',
  },
  {
    id: 'n12',
    type: 'billing',
    message: 'Payment received for Enterprise plan upgrade.',
    time: '3d ago',
    icon: CreditCard,
    color: 'text-emerald-500',
  },
  {
    id: 'n13',
    type: 'all',
    message: 'Warning: High memory usage detected on cluster worker nodes.',
    time: '3d ago',
    icon: ShieldAlert,
    color: 'text-amber-500',
  },
  {
    id: 'n14',
    type: 'system',
    message: 'Automated database backup completed.',
    time: '4d ago',
    icon: Database,
    color: 'text-blue-500',
  },
  {
    id: 'n15',
    type: 'all',
    message: 'New user joined: alex@starkindustries.com',
    time: '4d ago',
    icon: Activity,
    color: 'text-emerald-500',
  },
  {
    id: 'n5_dup',
    type: 'system',
    message: 'Database sync completed for Postgres production cluster.',
    time: '18m ago',
    icon: Activity,
    color: 'text-[var(--orbit-accent-primary)]',
  },
  {
    id: 'n6_dup',
    type: 'system',
    message: 'Lead score threshold reached for Alex Johnson.',
    time: '40m ago',
    icon: Zap,
    color: 'text-amber-500',
  },
  {
    id: 'n7_dup',
    type: 'all',
    message: 'Google Ads campaign sync completed. 1,240 new records found.',
    time: '3h ago',
    icon: CheckCircle2,
    color: 'text-emerald-500',
  },
];
